sudo: required

services:
  - docker

language: generic
before_install:
  - docker build -t kdubss/react-docker-demo -f Dockerfile.dev .	
  
script:
  - docker run -e CI=true kdubss/react-docker-demo npm run test -- --coverage