language: node_js
nvm:
  - 12.13.1

sudo: required

services:
  - docker

before_install:
  - docker build -t kdubss/react-docker-demo -f Dockerfile.dev .	
  
script:
  - docker run -e CI=true kdubss/react-docker-demo npm run test -- --coverage