version: '3'

services:

  # Frontend client-service container
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev       
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app

  # Testing Service container
  tests:
    build:
      # Run tests in current directory (i.e. /app in container)
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]