version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout

      - setup_remote_docker:

      - run:
          name: Setup Docker
          command: |
            docker build -t test -f Dockerfile.dev .